# Generated by Django 5.0.2 on 2024-02-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Types',
            new_name='Type',
        ),
    ]
